version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass

  api:
    image: ritoon/api-vote
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - db